# Generated by Django 5.2.16 on 2026-07-26 10:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(choices=[('educational', 'Educational'), ('communication', 'Communication'), ('professional', 'Professional')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['family', 'sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('edition', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(default='active', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('estimated_study_minutes', models.PositiveIntegerField(default=60)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studio.book')),
            ],
            options={
                'ordering': ['book__sequence', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('repository_path', models.CharField(max_length=500)),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('validation_status', models.CharField(choices=[('not_tested', 'Not tested'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_tested', max_length=20)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='studio.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('drafting', 'Drafting'), ('review', 'In Review'), ('approved', 'Approved'), ('published', 'Published'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20)),
                ('version', models.CharField(default='0.1', max_length=30)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('public_url', models.URLField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.assettype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('workflow_state', models.CharField(choices=[('planned', 'Planned'), ('drafting', 'Drafting'), ('educational_review', 'Educational Review'), ('media_production', 'Media Production'), ('quality_review', 'Quality Review'), ('ready', 'Ready for Publication'), ('published', 'Published'), ('revised', 'Revised')], default='planned', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gold_standard', models.BooleanField(default=False)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_unit', to='studio.chapter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studio.productionasset')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studio.productionunit')),
            ],
        ),
        migrations.AddField(
            model_name='productionasset',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.productionunit'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('public_url', models.URLField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='planned', max_length=20)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='studio.productionasset')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='studio.productionunit')),
            ],
        ),
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('technical', 'Technical'), ('educational', 'Educational'), ('editorial', 'Editorial'), ('publication', 'Publication')], max_length=20)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('findings', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='studio.productionasset')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='studio.productionunit')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('candidate', 'Candidate'), ('released', 'Released'), ('retired', 'Retired')], default='planned', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('production_units', models.ManyToManyField(related_name='releases', to='studio.productionunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='unique_book_chapter_number'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'slug'), name='unique_book_chapter_slug'),
        ),
        migrations.AddConstraint(
            model_name='productionasset',
            constraint=models.UniqueConstraint(fields=('production_unit', 'asset_type'), name='unique_asset_per_unit'),
        ),
    ]
