# Generated by Django 5.2.16 on 2026-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='execution_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='validation_message',
            field=models.TextField(blank=True),
        ),
    ]
